### ISSUE TITLE
Upgrade to protobuf-java 3.0.0 ( after Netty )

### ISSUE THREAD

**Issue by pjklauser** [pjklauser/protobuf-rpc-pro#38]
Support for protobuf 3.0.0. Currently protobuf-java is 3.0.0-alpha-3.1 (june 2015) when the definitive 3.0.0 version is out AND Netty supports it, we can think about upgrading.

**Comment by mdavis95** [comment]
From what I can tell Netty compiles fine with the protobuf-java 3.0.0-beta-1 and so does protobuf-rpc-pro.  I believe just depending on the new protobuf-java 3.0.0.-beta-1 will just work unless I am missing something.

**Comment by mdavis95** [comment]
https://github.com/google/protobuf/releases/tag/v3.0.2

**Comment by pjklauser** [comment]
Upgraded to 3.4.0 #38
