### ISSUE TITLE
protoc plugin that is being used

### ISSUE THREAD

**Issue by dtracers** [pjklauser/protobuf-rpc-pro#40]
I am trying to use the protoc with maven to generate the classes needed to use with your library but I am having trouble with it and I wanted to know if you were using a specific maven plugin to generate the java files from the protobuf.

Your Documentation reference a specific generated proto file but only post generation code exists.

It would be nice if the examples started with a proto file.

**Comment by pjklauser** [comment]
I have installed protoc.exe ( Google's download ) as an executable on the PATH on my build machine. Then to "build" the .proto files into java classes I use the shell script in /protobuf-rpc-pro-demo/bin/make-protos.sh

**Comment by dtracers** [comment]
Okay it appears that if you do not have:
```
option java_generic_services = true;
```
in your proto file it will not work.
I think it would be nice if this was in the doc area.
Also it appears the files in the docs reference the google code project and not the github folder.

**Comment by pjklauser** [comment]
You're right without  the java_generic_services option set, the resulting classes don't work ( or compile - i can't remember which ). I'll look to document this at the next opportunity.

**Comment by pjklauser** [comment]
i've added new docs and mentioned the option required in the IDL.
