### ISSUE TITLE
Is this project stable enough to use in production environment?

### ISSUE THREAD

**Issue by dawnbreaks** [pjklauser/protobuf-rpc-pro#47]
Hi, thank your for your working on this project. I am very excited about this project.  Is this project stable enough to use in production environment?

Thanks & Best Regards!

**Comment by Marax** [comment]
We are using this on quite big production environment for some time now, and so far no issues.

**Comment by dawnbreaks** [comment]
@Marax   Thanks very much. This project looks very good, and it 's awesome, and i will have a deep research on it.
